# =============================================================================
# HeadCNI Helm Chart Values Configuration
# =============================================================================
# This file defines all configuration options for HeadCNI, organized by functional modules

# =============================================================================
# 1. Container Image Configuration
# =============================================================================
image:
  # Image repository address
  # Type: string | Required: true | Example: "binrc/headcni:latest"
  repository: "binrc/headcni:latest"
  
  # Image pull policy: Always, IfNotPresent, Never
  # Type: string | Default: "IfNotPresent"
  pullPolicy: Always

# =============================================================================
# 2. Core Configuration
# =============================================================================
config:
  # =============================================================================
  # 2.1 Daemon Configuration
  # =============================================================================
  # Daemon basic configuration
  # - logLevel: Log level | Type: string | Default: "info"
  # - hostNetwork: Use host network | Type: boolean | Default: true
  daemon:
    logLevel: "info"              # Log level: debug, info, warn, error
    hostNetwork: true             # Use host network mode
  
  # =============================================================================
  # 2.2 HeadScale Configuration
  # =============================================================================
  # HeadScale is an open-source control server for Tailscale
  # - url: HeadScale server URL | Type: string | Required: true
  # - authKey: Authentication key (via Secret) | Type: string | Default: ""
  # - timeout: Connection timeout | Type: string | Default: "30s"
  # - retries: Connection retry count | Type: integer | Default: 3
  headscale:
    url: "https://headscale.example.com:8080"      # HeadScale server URL
    authKey: "YOUR_AUTH_KEY_HERE"                      # Authentication key (get from secret)
    timeout: "30s"                   # Connection timeout
    retries: 3                       # Connection retry count
  
  # =============================================================================
  # 2.3 Tailscale Configuration
  # =============================================================================
  # Tailscale client configuration
  # 
  # REQUIRED PARAMETERS:
  # - mode: Operation mode: "host" or "daemon" | Type: string | Required: true
  # - url: HeadScale server URL | Type: string | Required: true
  # 
  # OPTIONAL PARAMETERS:
  # - socket: Unix socket configuration | Type: object
  #   - name: Socket file name | Type: string | Default: "headcni_tailscale.sock"
  #   - path: Socket file path | Type: string | Default: "/var/run/headcni/headcni_tailscale.sock"
  # - hostname: Node hostname configuration | Type: object
  #   - prefix: Hostname prefix | Type: string | Default: "headcni-pod"
  #   - type: Hostname type: "hostname" or "fqdn" | Type: string | Default: "hostname"
  # - mtu: Maximum Transmission Unit | Type: integer | Default: 1280 | Range: 1280-1500
  # - acceptDNS: Accept DNS settings from HeadScale | Type: boolean | Default: false
  # - user: Tailscale username | Type: string | Default: "server"
  # - interfaceName: Tailscale interface name | Type: string | Default: "headcni01"
  # - tags: Node tags for access control | Type: array
  tailscale:
    mode: "daemon"               # Operation mode: host or daemon
    url: "https://headscale.example.com:8080"  # HeadScale server URL for daemon mode
    
    socket:
      name: "headcni_tailscale.sock"      # Socket file name
      path: "/var/run/headcni/headcni_tailscale.sock"  # Socket file path
    
    hostname:
      prefix: "headcni-pod"      # Hostname prefix
      type: "hostname"           # Hostname type: hostname or fqdn
    
    mtu: 1280                    # Maximum Transmission Unit
    acceptDNS: false              # Accept DNS settings from HeadScale
    overrideLocalDNS: false       # Override local DNS settings

    interfaceName: "headcni01"   # Tailscale interface name
    user: "server"               # Tailscale username
    tags:                        # Node tags for access control
      - "tag:control-server"
      - "tag:headcni"
  
  # =============================================================================
  # 2.4 Network Configuration
  # =============================================================================
  # Kubernetes cluster network configuration
  # 
  # REQUIRED PARAMETERS:
  # - podCIDR: Base Pod CIDR for the cluster | Type: string | Required: true | Format: CIDR
  # - serviceCIDR: Service CIDR for Kubernetes services | Type: string | Required: true | Format: CIDR
  # 
  # OPTIONAL PARAMETERS:
  # - mtu: Network interface MTU | Type: integer | Default: 1280 | Range: 1280-1500
  # - enableIPv6: Enable IPv6 support | Type: boolean | Default: false
  # - enableNetworkPolicy: Enable network policy support | Type: boolean | Default: true
  network:
    podCIDR: "10.42.0.0/16"     # Base Pod CIDR for the cluster (controlled by k8s/k3s)
    podCIDRSubnet: "/24"         # Subnet for the Pod CIDR
    serviceCIDR: "10.43.0.0/16"  # Service CIDR for Kubernetes services
    mtu: 1280                    # Network interface MTU
    enableIPv6: false            # Enable IPv6 support
    enableNetworkPolicy: true    # Enable network policy support
    
  # =============================================================================
  # 2.5 IPAM Configuration
  # =============================================================================
  # IP address management configuration
  # - type: IPAM type: "host-local" or "headcni-ipam" | Type: string | Required: true
  # - strategy: IP allocation strategy: "sequential", "random", "dense-pack" | Type: string | Default: "sequential"
  # - gcInterval: Garbage collection interval | Type: string | Default: "1h"
  ipam:
    type: "host-local"           # IPAM type: host-local or headcni-ipam
    strategy: "sequential"       # IP allocation strategy
    gcInterval: "1h"             # Garbage collection interval
  
  # =============================================================================
  # 2.6 DNS Configuration
  # =============================================================================
  # DNS resolution configuration
  dns:
    # MagicDNS configuration
    # - enabled: Enable MagicDNS | Type: boolean | Default: true
    # - nameservers: DNS server list | Type: array | Default: ["8.8.8.8", "8.8.4.4"]
    # - searchDomains: DNS search domains | Type: array | Default: ["cluster.local"]
    # - options: DNS resolution options | Type: array | Default: ["ndots:5", "timeout:2"]
    magicDNS:
      enabled: false               # Enable MagicDNS
      nameservers:               # DNS server list
        - "8.8.8.8"
        - "8.8.4.4"
      searchDomains:             # DNS search domains
        - "cluster.local"
      options:                   # DNS resolution options
        - "ndots:5"
        - "timeout:2"
      
  # =============================================================================
  # 2.7 Monitoring Configuration
  # =============================================================================
  # Monitoring and metrics collection configuration
  # - enabled: Enable monitoring | Type: boolean | Default: true
  # - port: Monitoring port | Type: integer | Default: 9001 | Range: 1-65535
  # - path: Metrics path | Type: string | Default: "/metrics"
  monitoring:
    enabled: true                # Enable monitoring
    port: 9001                   # Monitoring port
    path: "/metrics"             # Metrics path
  
  # =============================================================================
  # 2.8 Logging Configuration
  # =============================================================================
  # Logging configuration
  # - level: Log level | Type: string | Default: "info"
  # - format: Log format | Type: string | Default: "json"
  # - output: Log output | Type: string | Default: "stdout"
  # - file: File logging configuration | Type: object
  logging:
    level: "info"                # Log level: debug, info, warn, error
    format: "json"               # Log format: json, text
    output: "stdout"             # Log output: stdout, stderr, file
    file:
      enabled: false             # Enable file logging
      path: "/var/log/headcni/headcni.log"  # Log file path
      maxSize: "100MB"           # Maximum log file size
      maxBackups: 3              # Maximum number of backup files
      maxAge: "7d"               # Maximum age of log files
  
  # =============================================================================
  # 2.9 Security Configuration
  # =============================================================================
  # Security configuration
  # - tls: TLS configuration | Type: object
  # - auth: Authentication configuration | Type: object
  # - networkPolicy: Network policy configuration | Type: object
  security:
    tls:
      enabled: false             # Enable TLS
      certFile: ""               # TLS certificate file path
      keyFile: ""                # TLS private key file path
      caFile: ""                 # TLS CA certificate file path
    auth:
      enabled: false             # Enable authentication
      type: "token"              # Authentication type: token, basic, oauth
      token: ""                  # Authentication token
    networkPolicy:
      enabled: true              # Enable network policy
      ingress: []                # Ingress rules
      egress: []                 # Egress rules
  
  # =============================================================================
  # 2.10 Performance Configuration
  # =============================================================================
  # Performance configuration
  # - connectionPool: Connection pool configuration | Type: object
  # - cache: Cache configuration | Type: object
  # - concurrency: Concurrency configuration | Type: object
  performance:
    connectionPool:
      maxConnections: 100        # Maximum number of connections
      maxIdleConnections: 10     # Maximum number of idle connections
      connectionTimeout: "30s"   # Connection timeout
      idleTimeout: "90s"         # Idle connection timeout
    cache:
      enabled: true              # Enable caching
      size: "100MB"              # Cache size
      ttl: "1h"                  # Cache TTL
    concurrency:
      maxWorkers: 10             # Maximum number of worker goroutines
      queueSize: 100             # Maximum queue size
  
  # =============================================================================
  # 2.11 Advanced Permissions Configuration
  # =============================================================================
  # Advanced permissions for Kubernetes resources
  # - enabled: Enable advanced permissions | Type: boolean | Default: false
  # - description: Advanced permissions allow access to pods, services, and configmaps
  advancedPermissions:
    enabled: false               # Enable advanced permissions (pods, services, configmaps)
    description: "Advanced permissions are disabled by default for security"

# =============================================================================
# 3. Kubernetes Resource Configuration
# =============================================================================

# ServiceAccount configuration
# - create: Create ServiceAccount | Type: boolean | Default: true
# - name: ServiceAccount name | Type: string | Default: ""
serviceAccount:
  create: true                   # Create ServiceAccount
  name: ""                       # ServiceAccount name (leave empty for default)

# Resource limits configuration
resources:
  # Manager component resource requirements
  # - requests: Resource requests | Type: object
  #   - cpu: CPU request | Type: string | Default: "100m"
  #   - memory: Memory request | Type: string | Default: "128Mi"
  # - limits: Resource limits | Type: object
  #   - cpu: CPU limit | Type: string | Default: "200m"
  #   - memory: Memory limit | Type: string | Default: "256Mi"
  manager:
    requests:
      cpu: 100m                  # CPU request
      memory: 128Mi              # Memory request
    
    limits:
      cpu: 200m                  # CPU limit
      memory: 256Mi              # Memory limit
      
  # Metrics collection component resource requirements
  # - requests: Resource requests | Type: object
  #   - cpu: CPU request | Type: string | Default: "50m"
  #   - memory: Memory request | Type: string | Default: "64Mi"
  # - limits: Resource limits | Type: object
  #   - cpu: CPU limit | Type: string | Default: "100m"
  #   - memory: Memory limit | Type: string | Default: "128Mi"
  metrics:
    requests:
      cpu: 50m                   # CPU request
      memory: 64Mi               # Memory request
    
    limits:
      cpu: 100m                  # CPU limit
      memory: 128Mi              # Memory limit

# =============================================================================
# 4. Scheduling Configuration
# =============================================================================
# - nodeSelector: Node selector for deployment nodes | Type: object | Default: {}
# - tolerations: Tolerations for tainted nodes | Type: array | Default: [{"operator": "Exists", "effect": "NoSchedule"}]
# - priorityClassName: Priority class name | Type: string | Default: "system-node-critical"

nodeSelector: {}                  # Node selector for specifying deployment nodes

tolerations:                      # Tolerations for running on tainted nodes
  - operator: Exists
    effect: NoSchedule

priorityClassName: "system-node-critical"  # Priority class name